version: "3.3"
services:
  wordpress:
    build:
      context: ./config/wordpress
    volumes:
      - ./dist:/var/www/html
    ports:
      - "8090:80"
    restart: always
    working_dir: /var/www/html
    depends_on:
      - database
  database:
    build:
      context: ./config/database
    volumes:
      - datab:/var/lib/mysql
    restart: always
volumes:
    datab: {}
    dist: